### ISSUE TITLE
Disadvantages of simply increase MaxAge?

### ISSUE THREAD

**Issue by HanGuangXin** [ImmortalTracker/ImmortalTracker#3]
Hi, I'm interested in your work, but I have some questions I want to discuss with you.

As oc-sort said, the noise of kalman filter will increase with t^2 as long as there is no observations in update step, which makes the prediction of kalman filter not reliable anymore. So in my experiments in MOT17 dataset, simply increase MaxAge of lost trajectories will cause more wrong matches. 

What do you think of this question? Looking forward to your reply!

**Comment by Lzc6996** [comment]
@HanGuangXin 
Actually, motion prediction in 3D space is so much easier than in pixel space, that may be the key difference.

**Comment by HanGuangXin** [comment]
I see. Thanks a lot for your time!
