### ISSUE TITLE
What is the difference between this code and SimpleTrack?

### ISSUE THREAD

**Issue by hutao568** [ImmortalTracker/ImmortalTracker#5]
Hi, I'm very interested in your work ImmortalTracker, at the same time I'm following tusen's SimpleTrack, I wonder what is the difference between these two codebases? Except that the life cycle of the tracker in ImmortalTracker is infinite, I didn't find much difference elsewhere.

**Comment by Lzc6996** [comment]
You are right, this is the key difference. @hutao568
