### ISSUE TITLE
Training ImmortalTracker

### ISSUE THREAD

**Issue by Kampffussel03** [ImmortalTracker/ImmortalTracker#6]
Hi @ImmortalTracker,

Many thanks for your work!

I would like to reproduce you work and was wondering if you instructions for re-training? 

I assume you model needs training and not only the base detector. Please correct me if I am wrong here.

Best wishes

**Comment by esdolo** [comment]
Hi @Kampffussel03,

Immortal Tracker is a training-free 3D MOT algorithm with no trainable parameters (though it does rely on some hyper-parameters provided in configs).    

You only need the CenterPoint detection result to reproduce our reported tracking results.   You can also apply Immortal Tracker to any available detection results on WOD or nuScenes. 

Best wishes,
Qitai Wang
